### ISSUE TITLE
Not working at all on private trackers!

### ISSUE THREAD

**Issue by MozzieMD** [libragnar/ragnar#102]
I have some problems , the progress is always 0, so i checked the status.Error and it's unsupported URL protocol, what's the problem? even in sample client same thing, tested 2 private trackers! On piratebay it's working.

**Comment by patriksvensson** [comment]
See #99

**Comment by MozzieMD** [comment]
well there is nothing useful

**Comment by patriksvensson** [comment]
Did you really read what it said? Private trackers might be picky about what clients they accept.

**Comment by MozzieMD** [comment]
i know about that, and i know that most of the trackers use block list not allowed list, so there are blocked old clients that doesn't support DHT and so on, how can you get in that blacklist? and what user agent looks like and can it help if you are somehow blocked?

**Comment by vktr** [comment]
@MozzieMD it is quite hard to whitelist a client nowadays - most private trackers are super picky about what clients they allow. To get your client whitelisted, my guess is you need to contact each private tracker and start working them.

**Comment by MozzieMD** [comment]
@vktr maybe there is a way to make the tracker think that i'm from utorrent or other allowed clients?

**Comment by vktr** [comment]
@MozzieMD No
