### ISSUE TITLE
Could not load file or assembly "Ragner.dll"

### ISSUE THREAD

**Issue by snuswdk** [libragnar/ragnar#94]
Hi 

When I build my project and create a installer and install my application on win10 or win7 i get this error: 

System.IO.FileNotFoundException Could not load file or assembly "Ragner.dll" the specified module could not be found

I tried both using x86 or x64 when i build my application but it doesnt help. 

Any idea?

**Comment by vktr** [comment]
You need to deploy all assemblies in the output folder, (boost_*.dll and torrent.dll) as well.

**Comment by snuswdk** [comment]
My output folder contains theese files: 

boost_chrono-vc120-mt-1_55.dll
boost_date_time-vc120-mt-1_55.dll
boost_system-vc120-mt-1_55.dll
boost_thread-vc120-mt-1_55.dll
Ragnar.dll
Torrent.dll

I used nuget to include ragnar

**Comment by vktr** [comment]
Does the target machines have the Visual C++ 2013 redistributable installed?

**Comment by snuswdk** [comment]
No i didnt. It has now and everything seems to work now :+1:
