### ISSUE TITLE
errors while executing bootstrap.bat

### ISSUE THREAD

**Issue by tokalak** [libragnar/ragnar#98]
When executing bootstrap.bat (powsershell version 2) i get the following error:
       **Cannot bind the argument to the parameter "Path" ....**
The error is caused by this line: ```$LIBS_DIR = Join-Path $PSScriptRoot "packages"```

After changing ```$PSScriptRoot``` to ```PSScriptRoot``` i get this error:
       **Cannot find the type ```[System.IO.Compression.ZipFile] ...```**

Then i add the following line to the top of the file and get another error:
``` Add-Type -Path "C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.IO.Compression.FileSystem"```

**Add-Type : Couldn't add the parameter "Path" to the target. Cannot find the path C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.IO.Compression.FileSystem" ...**

**Comment by patriksvensson** [comment]
`$PSScriptRoot` is not supported in Powershell 2. 

Try assigning `$PSScriptRoot` like this:

```
$PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent
```

**Comment by tokalak** [comment]
Thank you for the suggestion.

Execution of the original ```bootstrap.bat``` with your changes leads to this error message:

``` The Typ [System.IO.Compression.ZipFile] cannot be found ... 
C:\Development\ragnar\run-bootstrap.ps1:36 symbol:36
    + [System.IO.Compression.ZipFile] <<<< ::ExtractToDirectory($file, $target)
    + CategoryInfo          : InvalidOperation: (System.IO.Compression.ZipFile:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound```

**Comment by patriksvensson** [comment]
Install Powershell 3? :)

**Comment by vktr** [comment]
Hi @tokalak, the build script is written for Powershell 3. If possible, it might be easier to update Powershell than to wrestle the build script :)

**Comment by tokalak** [comment]
@vktr thank you very much for the tip.
It worked very well.

**Comment by vktr** [comment]
Awesome :smiley:
